"""Safe artifact writing and bounded artifact result helpers."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path, PurePath

from infralink.cli.actions import action
from infralink.cli.contracts import (
    Action,
    Artifact,
    Binding,
    Page,
)
from infralink.cli.errors import CliFailure, ErrorCode
from infralink.cli.pagination import page_items, production_cursor_codec


def artifact_usage(message: str) -> CliFailure:
    return CliFailure(
        code=ErrorCode.USAGE_ERROR,
        message=message,
        exit_code=2,
        fix="Provide an explicit safe relative --output directory",
        next_actions=[
            action("help", ["infralink", "help"], "Show command output options"),
        ],
    )


def require_output(output: Path | None) -> Path:
    if output is None:
        raise artifact_usage("An explicit output directory is required")
    if output.is_absolute() or output == Path(".") or any(part == ".." for part in output.parts):
        raise artifact_usage("Output must be an unambiguous relative directory")
    if not output.parts or any(part in ("", ".") for part in output.parts):
        raise artifact_usage("Output must be an unambiguous relative directory")
    return output


def _safe_relative_file(path: Path) -> None:
    pure = PurePath(path)
    if pure.is_absolute() or not pure.parts or any(part in ("", ".", "..") for part in pure.parts):
        raise artifact_usage("Generated artifact path is unsafe")


def _preflight_directory(path: Path) -> None:
    current = Path()
    for part in path.parts:
        current /= part
        if current.is_symlink():
            raise artifact_usage("Output must not contain symlinks")
        if current.exists() and not current.is_dir():
            raise artifact_usage("Output path must contain only directories")


def write_artifacts(
    output: Path,
    generated: list[tuple[Path, str, bytes]],
) -> list[Artifact]:
    """Write generated bytes after validating every destination."""
    output = require_output(output)
    _preflight_directory(output)
    ordered = sorted(generated, key=lambda item: item[0].as_posix())
    destinations: list[tuple[Path, Path, str, bytes]] = []
    for relative, media_type, body in ordered:
        _safe_relative_file(relative)
        destination = output / relative
        _preflight_directory(destination.parent)
        if destination.is_symlink() or (destination.exists() and not destination.is_file()):
            raise artifact_usage("Generated artifact target is unsafe")
        destinations.append((relative, destination, media_type, body))

    for _relative, destination, _media_type, _body in destinations:
        destination.parent.mkdir(parents=True, exist_ok=True)
    artifacts: list[Artifact] = []
    no_follow = getattr(os, "O_NOFOLLOW", 0)
    for _relative, destination, media_type, body in destinations:
        try:
            descriptor = os.open(
                destination,
                os.O_WRONLY | os.O_CREAT | os.O_TRUNC | no_follow,
                0o644,
            )
            with os.fdopen(descriptor, "wb") as artifact_file:
                artifact_file.write(body)
        except OSError:
            raise artifact_usage("Generated artifact target is unsafe") from None
        artifacts.append(
            Artifact(
                path=destination.as_posix(),
                media_type=media_type,
                sha256=hashlib.sha256(body).hexdigest(),
            )
        )
    return artifacts


def artifact_fingerprint(
    *,
    command: str,
    sources: list[Path],
    options: dict[str, object],
    collections: dict[str, list[object]],
) -> str:
    source_digests = []
    for source in sources:
        try:
            digest = hashlib.sha256(source.read_bytes()).hexdigest()
        except OSError:
            digest = "unavailable"
        source_digests.append({"path": str(source), "sha256": digest})
    serialized = json.dumps(
        {
            "command": command,
            "sources": source_digests,
            "options": options,
            "collections": {
                name: [
                    item.model_dump(mode="json") if hasattr(item, "model_dump") else item
                    for item in items
                ]
                for name, items in collections.items()
            },
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(serialized).hexdigest()


def artifact_pages(
    *,
    command: str,
    collections: dict[str, list[object]],
    selected: str,
    cursor: str | None,
    limit: int,
    fingerprint: str,
) -> dict[str, Page[object]]:
    if selected not in collections:
        from infralink.cli.pagination import invalid_cursor

        raise invalid_cursor()
    if cursor is not None and len(collections) > 1 and not selected:
        from infralink.cli.pagination import invalid_cursor

        raise invalid_cursor()
    offset = (
        production_cursor_codec().decode(cursor, command, selected, fingerprint)
        if cursor is not None
        else 0
    )
    pages: dict[str, Page[object]] = {}
    for name, items in collections.items():
        collection_offset = offset if name == selected else 0
        page = page_items(items, limit=limit, offset=collection_offset, next_cursor="pending")
        if page.page.next_cursor is not None:
            page.page.next_cursor = production_cursor_codec().encode(
                command,
                name,
                collection_offset + limit,
                fingerprint,
            )
        pages[name] = page
    return pages


def continuation_actions(
    *,
    base_argv: list[str],
    limit: int,
    pages: dict[str, Page[object]],
    sources: dict[str, str],
) -> list[Action]:
    actions: list[Action] = []
    for name, page in pages.items():
        if page.page.next_cursor is None:
            continue
        actions.append(
            action(
                "continue",
                [
                    *base_argv,
                    "--collection",
                    name,
                    "--cursor",
                    "{cursor}",
                    "--limit",
                    str(limit),
                ],
                f"Continue {name}",
                bindings={
                    "cursor": Binding(
                        type="string",
                        required=True,
                        source=sources[name],
                    )
                },
            )
        )
    return actions
