"""Safe artifact writing and bounded artifact result helpers."""

from __future__ import annotations

import errno
import hashlib
import json
import os
import secrets
import stat
import sys
from dataclasses import dataclass
from pathlib import Path, PurePath

from infralink.cli.actions import action
from infralink.cli.contracts import (
    Action,
    Artifact,
    Binding,
    Page,
)
from infralink.cli.errors import CliFailure, ErrorCode
from infralink.cli.pagination import page_items, production_cursor_codec

_TRANSACTION_PREFIX = ".infralink-txn-"
_SECURE_ARTIFACT_WRITES_SUPPORTED = (
    sys.platform.startswith("linux")
    and hasattr(os, "O_DIRECTORY")
    and hasattr(os, "O_NOFOLLOW")
    and os.open in os.supports_dir_fd
    and os.mkdir in os.supports_dir_fd
    and os.rename in os.supports_dir_fd
    and os.rmdir in os.supports_dir_fd
    and os.stat in os.supports_dir_fd
    and os.unlink in os.supports_dir_fd
)


def artifact_usage(message: str) -> CliFailure:
    return CliFailure(
        code=ErrorCode.USAGE_ERROR,
        message=message,
        exit_code=2,
        fix="Provide an explicit safe relative --output directory",
        next_actions=[
            action("help", ["infralink", "help"], "Show command output options"),
        ],
    )


def artifact_write_failure() -> CliFailure:
    return CliFailure(
        code=ErrorCode.INTERNAL_ERROR,
        message="Artifact transaction failed",
        exit_code=74,
        fix="Retry the command after checking output storage",
    )


def artifact_platform_failure() -> CliFailure:
    return CliFailure(
        code=ErrorCode.PROVIDER_UNAVAILABLE,
        message="Secure artifact writes are unavailable on this platform",
        exit_code=69,
        fix="Run artifact-generating commands on a supported POSIX platform",
    )


def require_output(output: Path | None) -> Path:
    if output is None:
        raise artifact_usage("An explicit output directory is required")
    if output.is_absolute() or output == Path(".") or any(part == ".." for part in output.parts):
        raise artifact_usage("Output must be an unambiguous relative directory")
    if not output.parts or any(part in ("", ".") for part in output.parts):
        raise artifact_usage("Output must be an unambiguous relative directory")
    return output


def _safe_relative_file(path: Path) -> None:
    pure = PurePath(path)
    if pure.is_absolute() or not pure.parts or any(part in ("", ".", "..") for part in pure.parts):
        raise artifact_usage("Generated artifact path is unsafe")


def artifact_metadata(
    output: Path,
    generated: list[tuple[Path, str, bytes]],
) -> list[Artifact]:
    """Describe generated bytes without touching the filesystem."""
    output = require_output(output)
    artifacts = []
    seen: set[str] = set()
    for relative, media_type, body in sorted(
        generated,
        key=lambda item: item[0].as_posix(),
    ):
        _safe_relative_file(relative)
        normalized = relative.as_posix()
        if normalized in seen:
            raise artifact_usage("Generated artifact paths must be unique")
        seen.add(normalized)
        artifacts.append(
            Artifact(
                path=(output / relative).as_posix(),
                media_type=media_type,
                sha256=hashlib.sha256(body).hexdigest(),
            )
        )
    return artifacts


def _directory_flags() -> int:
    return os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW


def _path_or_write_failure(exc: OSError) -> CliFailure:
    if exc.errno in {errno.ELOOP, errno.ENOTDIR}:
        return artifact_usage("Output must contain only real directories")
    return artifact_write_failure()


def _preflight_directory(
    parent_fd: int,
    parts: tuple[str, ...],
) -> tuple[int, tuple[str, ...]]:
    """Open the longest existing prefix without mutating it."""
    current_fd = os.dup(parent_fd)
    try:
        for index, part in enumerate(parts):
            try:
                child_fd = os.open(part, _directory_flags(), dir_fd=current_fd)
            except FileNotFoundError:
                return current_fd, parts[index:]
            except OSError as exc:
                raise _path_or_write_failure(exc) from None
            os.close(current_fd)
            current_fd = child_fd
        return current_fd, ()
    except Exception:
        os.close(current_fd)
        raise


def _open_directory(
    parent_fd: int,
    parts: tuple[str, ...],
    created_directories: list[tuple[int, str]],
) -> int:
    """Open or create a descriptor-rooted directory chain."""
    current_fd = os.dup(parent_fd)
    try:
        for part in parts:
            try:
                child_fd = os.open(part, _directory_flags(), dir_fd=current_fd)
            except FileNotFoundError:
                try:
                    os.mkdir(part, 0o755, dir_fd=current_fd)
                except FileExistsError:
                    pass
                else:
                    created_directories.append((os.dup(current_fd), part))
                try:
                    child_fd = os.open(part, _directory_flags(), dir_fd=current_fd)
                except OSError as exc:
                    raise _path_or_write_failure(exc) from None
            except OSError as exc:
                raise _path_or_write_failure(exc) from None
            os.close(current_fd)
            current_fd = child_fd
        return current_fd
    except Exception:
        os.close(current_fd)
        raise


def _validate_target(parent_fd: int, filename: str) -> bool:
    try:
        target = os.stat(filename, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        return False
    except OSError:
        raise artifact_write_failure() from None
    if not stat.S_ISREG(target.st_mode):
        raise artifact_usage("Generated artifact target is unsafe")
    return True


@dataclass
class _TransactionTarget:
    relative: Path
    body: bytes
    existed: bool = False
    preflight_fd: int | None = None
    missing_parent_parts: tuple[str, ...] = ()
    parent_fd: int | None = None
    temporary: str | None = None
    backup: str | None = None
    backup_moved: bool = False
    committed: bool = False


def _remove_transaction_files(parent_fd: int) -> None:
    try:
        entries = os.listdir(parent_fd)
    except OSError:
        raise artifact_write_failure() from None
    for entry in entries:
        if not entry.startswith(_TRANSACTION_PREFIX):
            continue
        try:
            metadata = os.stat(entry, dir_fd=parent_fd, follow_symlinks=False)
            if stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
                os.unlink(entry, dir_fd=parent_fd)
        except FileNotFoundError:
            continue
        except OSError:
            raise artifact_write_failure() from None


def _unlink_if_present(parent_fd: int, name: str | None) -> None:
    if name is None:
        return
    try:
        os.unlink(name, dir_fd=parent_fd)
    except FileNotFoundError:
        pass


def _close_transaction(
    targets: list[_TransactionTarget],
    created_directories: list[tuple[int, str]],
    *,
    remove_directories: bool,
) -> None:
    for target in targets:
        if target.preflight_fd is not None:
            os.close(target.preflight_fd)
            target.preflight_fd = None
        if target.parent_fd is not None:
            os.close(target.parent_fd)
            target.parent_fd = None
    for parent_fd, name in reversed(created_directories):
        if remove_directories:
            try:
                os.rmdir(name, dir_fd=parent_fd)
            except OSError:
                pass
        os.close(parent_fd)


def write_artifacts(
    output: Path,
    generated: list[tuple[Path, str, bytes]],
) -> list[Artifact]:
    """Commit a descriptor-rooted batch or restore the previous filesystem state."""
    if not _SECURE_ARTIFACT_WRITES_SUPPORTED:
        raise artifact_platform_failure()
    output = require_output(output)
    metadata = artifact_metadata(output, generated)
    ordered = sorted(generated, key=lambda item: item[0].as_posix())
    targets = [
        _TransactionTarget(relative=relative, body=body) for relative, _media_type, body in ordered
    ]

    try:
        root_fd = os.open(".", _directory_flags())
    except OSError:
        raise artifact_write_failure() from None
    created_directories: list[tuple[int, str]] = []
    try:
        # Preflight every existing chain and target before the first mutation.
        try:
            for target in targets:
                parent_parts = (*output.parts, *target.relative.parts[:-1])
                target.preflight_fd, target.missing_parent_parts = _preflight_directory(
                    root_fd,
                    parent_parts,
                )
                if not target.missing_parent_parts:
                    target.existed = _validate_target(
                        target.preflight_fd,
                        target.relative.name,
                    )
        except (OSError, CliFailure):
            _close_transaction(targets, created_directories, remove_directories=False)
            raise

        transaction = secrets.token_hex(16)
        cleaned_parents: set[tuple[int, int]] = set()
        try:
            # Create missing directories and stage every body before committing any.
            for index, target in enumerate(targets):
                assert target.preflight_fd is not None
                target.parent_fd = _open_directory(
                    target.preflight_fd,
                    target.missing_parent_parts,
                    created_directories,
                )
                os.close(target.preflight_fd)
                target.preflight_fd = None
                identity = os.fstat(target.parent_fd)
                parent_identity = (identity.st_dev, identity.st_ino)
                if parent_identity not in cleaned_parents:
                    _remove_transaction_files(target.parent_fd)
                    cleaned_parents.add(parent_identity)
                target.temporary = f"{_TRANSACTION_PREFIX}{transaction}.tmp-{index}"
                descriptor = os.open(
                    target.temporary,
                    os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                    0o644,
                    dir_fd=target.parent_fd,
                )
                with os.fdopen(descriptor, "wb") as artifact_file:
                    artifact_file.write(target.body)

            # Commit with same-directory backups so every prior target is restorable.
            for index, target in enumerate(targets):
                assert target.parent_fd is not None
                assert target.temporary is not None
                if target.existed:
                    target.backup = f"{_TRANSACTION_PREFIX}{transaction}.bak-{index}"
                    os.replace(
                        target.relative.name,
                        target.backup,
                        src_dir_fd=target.parent_fd,
                        dst_dir_fd=target.parent_fd,
                    )
                    target.backup_moved = True
                os.replace(
                    target.temporary,
                    target.relative.name,
                    src_dir_fd=target.parent_fd,
                    dst_dir_fd=target.parent_fd,
                )
                target.temporary = None
                target.committed = True
        except (OSError, CliFailure):
            for target in reversed(targets):
                if target.parent_fd is None:
                    continue
                if target.committed:
                    _unlink_if_present(target.parent_fd, target.relative.name)
                if target.backup_moved and target.backup is not None:
                    try:
                        os.replace(
                            target.backup,
                            target.relative.name,
                            src_dir_fd=target.parent_fd,
                            dst_dir_fd=target.parent_fd,
                        )
                    except OSError:
                        pass
                    target.backup = None
                _unlink_if_present(target.parent_fd, target.temporary)
            _close_transaction(
                targets,
                created_directories,
                remove_directories=True,
            )
            raise artifact_write_failure() from None

        for target in targets:
            assert target.parent_fd is not None
            _unlink_if_present(target.parent_fd, target.backup)
        _close_transaction(
            targets,
            created_directories,
            remove_directories=False,
        )
    finally:
        os.close(root_fd)
    return metadata


def artifact_fingerprint(
    *,
    command: str,
    sources: list[Path],
    options: dict[str, object],
    collections: dict[str, list[object]],
) -> str:
    source_digests = []
    for source in sources:
        try:
            digest = hashlib.sha256(source.read_bytes()).hexdigest()
        except OSError:
            digest = "unavailable"
        source_digests.append({"path": str(source), "sha256": digest})
    serialized = json.dumps(
        {
            "command": command,
            "sources": source_digests,
            "options": options,
            "collections": {
                name: [
                    item.model_dump(mode="json") if hasattr(item, "model_dump") else item
                    for item in items
                ]
                for name, items in collections.items()
            },
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(serialized).hexdigest()


def artifact_pages(
    *,
    command: str,
    collections: dict[str, list[object]],
    selected: str,
    cursor: str | None,
    limit: int,
    fingerprint: str,
) -> dict[str, Page[object]]:
    if selected not in collections:
        from infralink.cli.pagination import invalid_cursor

        raise invalid_cursor()
    if cursor is not None and len(collections) > 1 and not selected:
        from infralink.cli.pagination import invalid_cursor

        raise invalid_cursor()
    offset = (
        production_cursor_codec().decode(cursor, command, selected, fingerprint)
        if cursor is not None
        else 0
    )
    pages: dict[str, Page[object]] = {}
    for name, items in collections.items():
        collection_offset = offset if name == selected else 0
        page = page_items(items, limit=limit, offset=collection_offset, next_cursor="pending")
        if page.page.next_cursor is not None:
            page.page.next_cursor = production_cursor_codec().encode(
                command,
                name,
                collection_offset + limit,
                fingerprint,
            )
        pages[name] = page
    return pages


def continuation_actions(
    *,
    base_argv: list[str],
    limit: int,
    pages: dict[str, Page[object]],
    sources: dict[str, str],
) -> list[Action]:
    actions: list[Action] = []
    for name, page in pages.items():
        if page.page.next_cursor is None:
            continue
        actions.append(
            action(
                "continue",
                [
                    *base_argv,
                    "--collection",
                    name,
                    "--cursor",
                    "{cursor}",
                    "--limit",
                    str(limit),
                ],
                f"Continue {name}",
                bindings={
                    "cursor": Binding(
                        type="string",
                        required=True,
                        source=sources[name],
                    )
                },
                safe=False,
            )
        )
    return actions
