"""D2 diagram generation."""

from __future__ import annotations

from collections import defaultdict
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from infralink.core.edges import EdgeSet
    from infralink.core.registry import Host, Registry


def generate_d2(
    hosts: list[Host],
    edges: EdgeSet,
    registry: Registry,
) -> str:
    """
    Generate D2 diagram.

    D2 is a modern diagram scripting language.
    See: https://d2lang.com/
    """
    lines = [
        "# Infrastructure Topology",
        "# Generated by infralink",
        "",
        "direction: right",
        "",
    ]

    # Group hosts
    groups: dict[str, list[Host]] = defaultdict(list)
    for host in hosts:
        group = host.group or "other"
        groups[group].append(host)

    # Define groups as containers
    for group, group_hosts in sorted(groups.items()):
        lines.append(f"{group}: {{")
        lines.append(f"  label: {group.upper()}")
        lines.append("  style: {{")
        lines.append("    fill: transparent")
        lines.append("    stroke: '#888'")
        lines.append("    stroke-dash: 3")
        lines.append("  }}")
        lines.append("")

        for host in sorted(group_hosts, key=lambda h: h.canonical_name):
            node_id = host.uuid[:8]
            lines.append(f"  {node_id}: {{")
            lines.append(f"    label: {host.canonical_name}")
            lines.append("    shape: rectangle")

            # Add services as nested items (limit to 5)
            services = host.services[:5]
            if services:
                for svc in services:
                    svc_id = svc.replace("-", "_")
                    lines.append(f"    {svc_id}: {svc}")

            lines.append("  }}")

        lines.append("}}")
        lines.append("")

    # Add edges
    lines.append("# Connections")
    seen_edges: set[tuple[str, str]] = set()

    for edge in edges:
        if edge.is_wildcard_source():
            continue

        target_id = edge.target_host[:8]
        target_host = registry.get_by_uuid(edge.target_host)
        target_group = target_host.group if target_host else "other"

        for source_uuid in edge.source_hosts:
            source_id = source_uuid[:8]
            source_host = registry.get_by_uuid(source_uuid)
            source_group = source_host.group if source_host else "other"

            # Skip duplicates
            edge_key = (source_id, target_id)
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)

            # Check if both hosts are in our list
            source_in_list = any(h.uuid.startswith(source_id) for h in hosts)
            target_in_list = any(h.uuid.startswith(target_id) for h in hosts)

            if not (source_in_list and target_in_list):
                continue

            # Build connection
            source_path = f"{source_group}.{source_id}"
            target_path = f"{target_group}.{target_id}"

            # Style based on criticality
            style = ""
            if edge.is_critical:
                style = " { style.stroke: '#e74c3c'; style.stroke-width: 2 }"

            label = f"{edge.target_service}:{edge.target_port}"
            lines.append(f"{source_path} -> {target_path}: {label}{style}")

    return "\n".join(lines)
